# Generated by Django 4.2.16 on 2024-10-30 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="camera",
            old_name="IP",
            new_name="ip",
        ),
    ]
