# Generated by Django 4.2.16 on 2024-10-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_workshift"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="generated_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
